site_name: Emmetthor's Competitive Programming Skills

theme:
  name: material
  palette:
    - scheme: slate
      primary: custom
      accent: custom

  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.integrate

nav:
  - 首頁: index.md
  - 想法與策略:
    - 競賽策略: mindset/contest_technique.md
  - 實作技巧:
    - 實作規則: implementation/implementation_rule.md
  - 解題技巧:
    - 總覽: techniques\index.md
    - 數學:
      - 取餘: techniques\math\modulo.md
      - 質數: techniques\math\prime.md
      - 組合數: techniques\math\combinatorics.md
      - 等價類計數: techniques\math\counting_equivalent_states.md
      - 數學式化簡: techniques\math\equation_optimize.md
      - 排容原理: techniques\math\inclusion_exclusion.md
    - 前綴和與差分:
      - 前綴和: techniques\prefix_sum_and_difference\prefix_sum.md
      - 差分: techniques\prefix_sum_and_difference\difference.md
    - 動態規劃 dp:
      - dp 初探: techniques/dp/dp_introduce.md
      - dp 狀態設計: techniques/dp/dp_state_design.md
      - 背包問題: techniques/dp/knapsack.md
      - 二維地圖 dp: techniques/dp/path_on_grid.md
      - 區間 dp: techniques/dp/range_dp.md
    - 圖論:
      - 圖論建模: techniques\graph\graph_theory_modeling.md
      - 找環: techniques\graph\graph_theory_modeling.md
    - 最短路:
      - Floyd Warshall: techniques\shortest_path\floyd_warshall.md
    - 排序與交換:
      - 交換技巧: techniques\swap_linked_technique.md
  - 解題筆記:
    - 總覽: problem_solutions\index.md
    - Atcoder Beginner Contest:
      - ABC452:
        - ABC452E: problem_solutions\ABC\452\ABC452E.md
      - ABC455:
        - ABC455E: problem_solutions\ABC\455\ABC455E.md
    - LeetCode: 
      - 2033: problem_solutions\LeetCode\LeetCode2033.md
  - 一頁式筆記: lite.md

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
      toc_depth: 4

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - web_codes/javascripts/mermaid_init.js
  
extra_css:
  - web_codes/stylesheets/extra.css
